### ISSUE TITLE
Добавляем скрипты для GH Actions

### ISSUE THREAD

**Issue by eroshenkoam** [eroshenkoam/java-cmd#5]
Скрипт для сборки в файле `.github/workflows/build.yml`: 
```
name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "Build"
      run: ./gradlew nativeImage
```

Скрипт для релиза в файле `.github/workflows/release.yml`: 
```
name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build"
        run: ./gradlew nativeImage
      - name: "Upload binaries"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/graal/tester
          asset_name: tester_${{ matrix.os }}
          asset_content_type: application/octet-stream
```
